In [2]:
print("Hello")

Hello


In [3]:
print(2)

2


In [3]:
x=(1,2,3,4,5,6,7)
a=int(input('Enter number'))
for i in range(len(x)):
    if a==x[i]:
        print('number found')
    else():
        print('not found')

SyntaxError: invalid syntax (<ipython-input-3-9cbfc7720e82>, line 6)

In [2]:
a={0:'sagar',1:'indira',2:3}
a.values()
a.get(1)
b={3:'super'}


dict_values(['sagar', 'indira', 3])

In [10]:
a=int(input('Enter marks of the student:'))
if a<10:
    print('student has failed the exam')
elif a>=10 and a<20:
    print('student has aquired C grade')
elif a>=20 and a<=30:
    print('student has aquired B grade')
else:
    print('student has aquired A grade')
            

Enter marks of the student:20
student has aquired B grade


In [11]:
count=0
while(count<50):
    print('The count is:',count)
    count=count+1
    

The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8
The count is: 9
The count is: 10
The count is: 11
The count is: 12
The count is: 13
The count is: 14
The count is: 15
The count is: 16
The count is: 17
The count is: 18
The count is: 19
The count is: 20
The count is: 21
The count is: 22
The count is: 23
The count is: 24
The count is: 25
The count is: 26
The count is: 27
The count is: 28
The count is: 29
The count is: 30
The count is: 31
The count is: 32
The count is: 33
The count is: 34
The count is: 35
The count is: 36
The count is: 37
The count is: 38
The count is: 39
The count is: 40
The count is: 41
The count is: 42
The count is: 43
The count is: 44
The count is: 45
The count is: 46
The count is: 47
The count is: 48
The count is: 49


In [3]:
def fahrenheit(T_in_celsius):
    return(T_in_celsius*9/5)+32
for t in (24,32.5,4.7,40):
    print(t,":",fahrenheit(t))

24 : 75.2
32.5 : 90.5
4.7 : 40.46
40 : 104.0


In [13]:
a=[]
for i in range(0,5,1):
    print (i)
    x=int(input('enter the numbers'))
    a.append(x)
def add(a):
    c=0
    for i in a:
        c=c+i
        print("total",c)
#print("total is:",c)
add(a)

0
enter the numbers3
1
enter the numbers4
2
enter the numbers5
3
enter the numbers6
4
enter the numbers7
total 3
total 7
total 12
total 18
total 25


In [15]:
def f():
    h="perl"
    return(h)
s="pytohn"
f()
#print(h)
print(s,h)


NameError: name 'h' is not defined

In [4]:
#result_str="";
for i in range(0,5):
    if(i<=0 and i>5):
        print("*\n",i)
for i in range(0,5):
    if(i>=5 and i<9):
        print("*\t",i)

In [12]:
fileobject=open('python_tutorial.txt',"r")
print(fileobject)
fileobject.read()
#fileobject.write("im from indira college")

<_io.TextIOWrapper name='python_tutorial.txt' mode='r' encoding='cp1252'>


'im from indira collegeim from indira college'

In [13]:
c=3/0

ZeroDivisionError: division by zero

In [15]:
a="sagar"
try:
    b=a+3
except:
    
    print("Error found")

Error found


In [4]:
a=int(input('Enter value of a:'))
b=int(input('Enter value of b:'))
if  a==b:
    print('a and b are same')
    

Enter value of a:4
Enter value of b:4
a and b are same


In [6]:
a=int(input('Enter value of a:'))
b=int(input('Enter value of b:'))
if b==a:
    print('a and b are same')
    
    
else:
    print("a and b are not same")
        

Enter value of a:3
Enter value of b:4
a and b are not same


In [8]:
a=int(input("Enter input"))
if a%2==0:
    print('even')
    
else:
    print('odd')
    
    

Enter input31
odd


In [10]:
result=''
for i in range(0,6):
    for j in range(0,6):
        if(j==1 or(i==5 and j!=0 and j<6)):
            result=result+" *"
        else:
            result=result+""
    result=result+"\n"
print(result)
      
   


 *
 *
 *
 *
 *
 * * * * *



In [27]:
a=int(input("enter rows"))
b=int(input("enter column"))
s=''
for i in range(0,a):
    for j in range(0,b):
        if(((i==0 and j==0)or(i==0 and j==4))or((i==4 and j==0)or(i==4 and j==4))or(i==2 and j==2)or(i==1 and j==1)or(i==3 and j==3)or(i==3 and j==1)or(i==1 and j==3)):
            s =s+"*"
        else:
            s=s+" "
    s=s+"\n"
print(s)
             


*   *
 * * 
  *  
 * * 
*   *



In [28]:
a=int(input("enter number:"))
def square(a):
    c=a*a
    return c
ans=square(a)
print(ans)

enter number:4
16


In [32]:
import math
a=int(input("enter number:"))
def squareroot(a):
    c=math.sqrt(a)
    return c
ans=squareroot(a)
print(ans)

enter number:16
4.0


In [43]:
import math
a=int(input("Enter number:"))
class calculator:
   
    def square(a):
        c=a*a
        return c
    def squareroot(a):
        c=math.sqrt(a)
        return c
#ans=square(a)
#ans1=squareroot(a)
m=calculator.square(a)
n=calculator.squareroot(a)
print(m)
print(n)

Enter number:4
16
2.0


In [53]:
a=[]
for i in range(0,5):
    b=int(input("enter numbers"))
    a.append(b)
def mult(a):
    c=1
    for i in a:
        print(i)
        c=c*i
    return c
ans=mult(a)
print(ans)


enter numbers2
enter numbers2
enter numbers2
enter numbers2
enter numbers2
2
2
2
2
2
32


In [3]:
import numpy as np



In [4]:
np.__version__

'1.16.4'

In [5]:
np?

In [17]:
#np.array([1,3,5,6,8,9])

np.array([1,3,4,5.983984759357,5], dtype='float64')



array([1.        , 3.        , 4.        , 5.98398476, 5.        ])

In [18]:
np.zeros(10, dtype =int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
np.diag((4,4), 1)

array([[0, 4, 0],
       [0, 0, 4],
       [0, 0, 0]])

In [39]:
np.random.random((3,3,3,3))

array([[[[0.09424961, 0.27636146, 0.22866264],
         [0.23626226, 0.43907377, 0.07374991],
         [0.3825487 , 0.50414267, 0.24344107]],

        [[0.21513428, 0.07598102, 0.02578963],
         [0.54664279, 0.80738351, 0.88553123],
         [0.66324418, 0.65685783, 0.75052703]],

        [[0.73860313, 0.09591052, 0.17731309],
         [0.77451752, 0.82801114, 0.38727316],
         [0.56282969, 0.93807583, 0.11819938]]],


       [[[0.05736   , 0.89337678, 0.08143604],
         [0.04726761, 0.16176644, 0.66019587],
         [0.44242558, 0.07938656, 0.49077065]],

        [[0.36679075, 0.35850992, 0.15320375],
         [0.1203279 , 0.99956609, 0.86076337],
         [0.63130626, 0.86345781, 0.2427062 ]],

        [[0.1116053 , 0.78918828, 0.66948022],
         [0.91684028, 0.07556261, 0.2557352 ],
         [0.6004389 , 0.98194662, 0.47253985]]],


       [[[0.93887508, 0.92478904, 0.74934314],
         [0.17330066, 0.5416776 , 0.60843994],
         [0.3935808 , 0.14119856, 0.8789062 

In [28]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [37]:
np.linspace(-0.7,0.6,3)

array([-0.7 , -0.05,  0.6 ])

In [45]:
np.random.randint(4,20,(4,5))

array([[ 4, 17, 17, 18, 11],
       [12,  6, 15,  7, 15],
       [ 4, 11, 17,  8, 11],
       [10, 10, 16,  8, 12]])

In [46]:
np.random.normal(4,12,(3,3))

array([[ -7.62556887,   6.99827968,   5.63630738],
       [  7.98156221, -23.66277607,   9.00420441],
       [  0.90864178, -14.24567443,   5.94415881]])

In [51]:
np.eye(9,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
print(max('hello'))

o


In [89]:
marks={'sagar':[49,49],'taral':[43,41],'pratik':[45,37],'hitesh':[24,45]}
avg=(marks['sagar'][0]+marks['sagar'][1])
avg1=(marks['taral'][0]+marks['taral'][1])
avg2=(marks['pratik'][0]+marks['pratik'][1])
avg3=(marks['hitesh'][0]+marks['hitesh'][1])
a=(avg,avg1,avg2,avg3)
c=max(a)
per=(avg/c)*100
per1=(avg1/c)*100
per2=(avg2/c)*100
per3=(avg3/c)*100
print(per,per1,per2,per3)


100.0 85.71428571428571 83.6734693877551 70.40816326530613


In [94]:
perL = [per,per1,per2,per3]
for i in range(4):
    print(list(marks.keys()[i]+ str(perL[i])) 

SyntaxError: unexpected EOF while parsing (<ipython-input-94-cee95b13737c>, line 3)

In [95]:
[x+y for x in [10,30,50] for y in[30,10,20]]

[40, 20, 30, 60, 40, 50, 80, 60, 70]